#
#    
#    ███████╗ █████╗  ██████╗██╗   ██╗  ██████╗  █████╗ ██╗   ██╗███╗   ███╗███████╗███╗  ██╗████████╗ ██████╗
#    ██╔════╝██╔══██╗██╔════╝╚██╗ ██╔╝  ██╔══██╗██╔══██╗╚██╗ ██╔╝████╗ ████║██╔════╝████╗ ██║╚══██╔══╝██╔════╝
#    █████╗  ███████║╚█████╗  ╚████╔╝   ██████╔╝███████║ ╚████╔╝ ██╔████╔██║█████╗  ██╔██╗██║   ██║   ╚█████╗ 
#    ██╔══╝  ██╔══██║ ╚═══██╗  ╚██╔╝    ██╔═══╝ ██╔══██║  ╚██╔╝  ██║╚██╔╝██║██╔══╝  ██║╚████║   ██║    ╚═══██╗
#    ███████╗██║  ██║██████╔╝   ██║     ██║     ██║  ██║   ██║   ██║ ╚═╝ ██║███████╗██║ ╚███║   ██║   ██████╔╝
#    ╚══════╝╚═╝  ╚═╝╚═════╝    ╚═╝     ╚═╝     ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝╚══════╝╚═╝  ╚══╝   ╚═╝   ╚═════╝ 
#
#               The official payment processing implementation as alternative for the RCON protocol
#                                  © EasyDonate 2020-2021 - All rights reserved
#
#
# Уникальный ключ вашего магазина
key: ''

# Идентификатор вашего сервера, информацию о
# платежах для которого будет получать плагин
server-id: 0

# Частота обращений к API для получения списка последних платежей
# Указывается в минутах, не может быть менее 1 минуты
request-frequency: 1

# Максимальное количество неудачных попыток повторить загрузку репорта после
# которых он будет выгружен из кэша, а вы получите сообщение об ошибке в консоли
# (?) Значение '0' отключает кэширование неудачных запросов
max-failed-attempts: 10

# Уровень прав для внутреннего исполнителя команд
# Значение эквивалентно 'op-permission-level' в server.properties
# 
# Список значений, используемых кодом игры:
# 1 - Обход spawn-protection
# 2 - Доступ к КБ, /clear, /gamemode и др.
# 3 - Доступ к /(de)op, /ban, /kick
# 4 - Доступ к /stop
#
# Значение '4' и выше даст исполнителю доступ ко всем командам
# Также, при проверке наличия прав у этого исполнителя ответ от методов в коде игры
# будет всегда положительный, т.е., фактически, исполнитель имеет все права
permission-level: 4

# Вывод дополнительных сообщений в консоли
logging:
  # Режим отладки
  debug: false
  # Оповещения о репортах, загрузить которые по какой-то причине не удалось
  query-task-errors: true
  # Предупреждение о неудачных попытках загрузки кэшированных репортов
  cache-worker-warnings: true
  # Оповещения об удалении кэшированных репортов, которые не удалось загрузить указанное кол-во раз
  cache-worker-errors: true